version: '3.8'

services:
  # Aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-sender-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - cv-sender-network
    depends_on:
      - database
      - redis

  # Servidor Web Nginx
  webserver:
    image: nginx:alpine
    container_name: cv-sender-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cv-sender-network
    depends_on:
      - app

  # Banco de Dados PostgreSQL
  database:
    image: postgres:15
    container_name: cv-sender-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cv_sender
      POSTGRES_USER: cv_sender
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - cv-sender-network

  # Redis para Cache e Sessões
  redis:
    image: redis:alpine
    container_name: cv-sender-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cv-sender-network

  # Node.js para build dos assets
  node:
    image: node:18-alpine
    container_name: cv-sender-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - cv-sender-network
    profiles:
      - development

# Volumes persistentes
volumes:
  postgres:

# Rede customizada
networks:
  cv-sender-network:
    driver: bridge
